### ISSUE TITLE
Project popover: missing "escape_text" property

### ISSUE THREAD

**Issue by bitseater** [alainm23/planner#18]
When I click on the _Project_ button and launch the associated popover, i can see the name and description of the project. The description use markup language, the `Gtk.Label` have defined the property `use_markup` , but i can see the code into description. I use characters like "&" or "+".

<a href="https://imgur.com/oLoItJt"><img src="https://i.imgur.com/oLoItJt.png" title="source: imgur.com" /></a>

To use markup from external text or text given by users, first you must escape the string, like in the example:
```
    var label = new Gtk.Label ("");
    label.label = "<small>" + GLib.Markup.escape_text ("Client built in Vala & Gtk+", -1) + "</small>";
    label.use_markup = true;
```

Continue this way. It's a good project.

**Comment by alainm23** [comment]
Wao, te prepondere en español ya que se que eres de España xd, la verdad no había visto este bug. Muchas gracias por reportarlo, la verdad quitare esa descripción y pondré un Gtk.Label con la ultima actualización el proyecto (Ultima actualización hoy, ayer, hace 'n' dias) ya que la descripción ya se ve en la vista general.

**Comment by bitseater** [comment]
Si te sirve mi opinión, me parece buena idea. Si necesitas algo, no dudes en preguntar. Saludos.

**Comment by alainm23** [comment]
Muchas gracias, ya esta corregido.
