### ISSUE TITLE
Suggested UX Enhancements

### ISSUE THREAD

**Issue by Alecaddd** [alainm23/planner#20]
After using it for a bit I'd love to suggest some features that would improve the overall user experience and make the app easier and faster to use.

* Double click on list name in the sidebar to open the edit dialog.
* Whenever there's an input text, hitting the Enter key on the keyboard, should trigger the same "save" action of the related button.
* Highlight the currently selected List.
* Make the List sidebar resizable.
* Use `label.set_ellipsize (Pango.EllipsizeMode.END);` when the List name is longer than the container in order to have the Task counter always visible even if the sidebar is small.
* Show expand/collapse hint when hovering on a task.
* Add rollover UI hints, like increase/decrease opacity, background color rollover, etc., to improve usability.

Cheers

**Comment by alainm23** [comment]
Thank you very much for trying Planner, the feedback is always good. I will cover your requests in a new version and other improvements in UX that is coming.
