### ISSUE TITLE
HUGE headerbar

### ISSUE THREAD

**Issue by aggalex** [alainm23/planner#29]
You window uses a huge headerbar that takes up too much vertical space. I suspect you have applied too much top and bottom margin to your project icon image, making the headerbar go really fat. Perhaps you'd like to lessen that margin or something, since it's hard to use your app in computers with small screens (which is sad, because your app is one of the best diamonds appcenter can offer! :1st_place_medal: ).

**Comment by aggalex** [comment]
After exploring your code, I found out that the headerbar resides in the widgets/headerbar.vala file, which has the icon of the project (I think you called this "avatar"), which is attached to a grid, which is then added to the headerbar. But that grid has a margin of 12 pixels (!), and that makes it truly wide. How about using different margins for left, right, top and bottom, making top and bottom margins ~6px and leaving right & left margins at 12px. See if that will solve the propblem,.

**Comment by alainm23** [comment]
This is a big UX problem, I could send me an image to be able to better review the problem.

**Comment by alainm23** [comment]
I could compile this new version, let me know if the problem continues, and if possible attach a photo please.
`git clone -b dev https://github.com/alainm23/planner.git
cd planner
meson build --prefix=/usr
cd build
sudo ninja install
com.github.alainm23.planner
`

**Comment by aggalex** [comment]
Will do when I find the time

**Comment by alainm23** [comment]
Thank you, I'm looking forward for your answer.

**Comment by aggalex** [comment]
Boy you sure have lots of dependencies! I had to install the *-dev versions one by one. Anyway, that UI change was a bit... unexpected. It works though!!! In my 1266x768 display, the headerbar looks perfect! Here's the screenshots I promised you:
![screenshot from 2018-05-07 19 53 53](https://user-images.githubusercontent.com/11951328/39713798-bc87d272-5230-11e8-95bb-2003b710c6d8.png)
![screenshot from 2018-05-07 19 56 05](https://user-images.githubusercontent.com/11951328/39713800-bcdeb0e2-5230-11e8-9f2e-6849fdb8a9bd.png)
Of course with this design there are more problems to address asside from making it work. Nothing to do with the headerbar, but just generally UI & UX problems. These are:

1. The left and right margins of the Projects list is incoherent. Perhaps you would like to move the separator bar a little bit to the right applying more right margin to the grid containing everything to the left of the separator, or remove ether the shadow from behind the list or the separator. BTW, a shadow is used in Design to separate a focused element from the others, and a separator is used to separate groups of elements. I can understand why you're using both, but when there is a shadow right next to a separator just like in your Today overview, there is double, incoherent separation, which is obviously bad. So, ether make them be more far away, or remove one of them.
![njk](https://user-images.githubusercontent.com/11951328/39715342-9ccf442e-5235-11e8-9b45-65aeae3f39a9.png)

2. When creating a new project, the "details" field looks ugly, since it has no border and is white while the background is black. Now, I've read in your NewEditProject.vala popover code you use a Gtk.TextView for that, which is totally not fitting the situation, as the user won't need to apply formatting to the "Description" text, like bold or italics or size. The only thing they will need is to write a short, ~10 word description for the project, so a Gtk.Entry with a big height will do the job better and more consistently.
![asjhklcoi](https://user-images.githubusercontent.com/11951328/39715408-d310a924-5235-11e8-9bfc-614dcea3b74c.png)

3. The shadow in the projects list is crudely cut, making blending between the background and the shadow color too crude, thus making the shadow look too fake.

That's all!! if you'd like me to make new threads about these problems, tell me.

**Comment by alainm23** [comment]
Problem 1: The idea is to make it clean, In Loki add the class Gtk.PopOver solves the problem, for Juno I have another solution
![planner -1](https://user-images.githubusercontent.com/33765137/39715882-47e12676-51f4-11e8-83e3-ebfd6c12a984.png)

Problem 2: Problem 2: This is a UX problem. You are right, I will use Gtk.Entry since a description does not require formatting.

Problem 3: It is solved together with problem 2

**Comment by aggalex** [comment]
Perfection! Thank you for your time.
