### ISSUE TITLE
Use libGDA to manage database

### ISSUE THREAD

**Issue by alainm23** [alainm23/planner#4]
I will start the migration to libGDA to be able to work in the database, this will give me the possibility of being able to export and import the information in an easier way.

**Comment by Alecaddd** [comment]
Just FYI, LibGDA hasn't seen an update since 2013, and it shows.
Sequeler is based on LibGDA and I had so many issues with outdated commands, mismatching column data, and so on.
If the type of data is fully controlled by you and not the user, you should be fine.

**Comment by alainm23** [comment]
Haha, I think I'll close this, I'm not working on libGDA and I see more complicated migration.
